/* Self-contained styled PDF export: mirrors the website's blue/teal hierarchy, without external libraries. */
(function(global){'use strict';
const clean=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/\u2022/g,'-').replace(/[^\x20-\x7e]/g,'?');
const labels={primary:'Answer',repeat:'Entries',purpose:'Primary purpose',transformationTypes:'Transformation types',otherTransformation:'Other transformation',source:'Where the data comes from',target:'Where the data goes',sourceFormat:'Current data format / schema',targetFormat:'Required data format / schema',details:'Additional details',direction:'Direction',frequency:'Frequency',directionDetails:'Direction - more details (optional)',frequencyDetails:'Frequency - more details (optional)'};
const usageFields={projectUsers:'CircSmeltSteel project work - number of users',projectVolume:'CircSmeltSteel project work - estimated data volume',projectFrequency:'CircSmeltSteel project work - upload frequency',projectFrequencyOther:'CircSmeltSteel project work - other frequency',projectCompute:'CircSmeltSteel project work - compute needs',productionUsers:'Regular operational/production use - number of users',productionVolume:'Regular operational/production use - estimated data volume',productionFrequency:'Regular operational/production use - upload frequency',productionFrequencyOther:'Regular operational/production use - other frequency',productionCompute:'Regular operational/production use - compute needs'};
const systemFields={'field-1':'System/tool name','field-2':'Owner/contact','field-3':'Purpose of connection','field-4':'Data exchanged','field-17':'Current data format','field-18':'Existing interface / API / protocol','field-19':'Other information / unknowns'};
const keyLabel=(key,qid)=>qid==='s3q11'&&systemFields[key]?systemFields[key]:(usageFields[key]||labels[key]||key.replace(/^field-/, 'Field ').replace(/^options-/, 'Selected options ').replace(/^followup-/, 'Follow-up ').replace(/::purpose$/, ' - primary purpose').replace(/::other$/, ' - other details'));
const rgb=h=>{const v=h.replace('#','');return [0,2,4].map(i=>(parseInt(v.slice(i,i+2),16)/255).toFixed(3)).join(' ')};
const esc=s=>clean(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
function makePdf(result){
 const W=595,H=842,L=44,R=44,B=52,usable=W-L-R;
 const colors={navy:'#153e57',teal:'#217a79',ink:'#203448',muted:'#536c7a',pale:'#eef7f5',line:'#d8e5e9',white:'#ffffff'};
 const pages=[];let cmds=[],y=H-43,number=0;
 const rect=(x,b,w,h,color)=>cmds.push(rgb(color)+' rg '+x.toFixed(1)+' '+b.toFixed(1)+' '+w.toFixed(1)+' '+h.toFixed(1)+' re f');
 const line=(x1,b1,x2,b2,color)=>cmds.push(rgb(color)+' RG 0.6 w '+x1+' '+b1.toFixed(1)+' m '+x2+' '+b2.toFixed(1)+' l S');
 const txt=(s,x,b,size=10,bold=false,color=colors.ink)=>cmds.push('BT '+rgb(color)+' rg /'+(bold?'F2':'F1')+' '+size+' Tf 1 0 0 1 '+x.toFixed(1)+' '+b.toFixed(1)+' Tm ('+esc(s)+') Tj ET');
 const footer=()=>{line(L,39,W-R,39,colors.line);txt('Materials Commons  |  Infrastructure assessment',L,26,8,false,colors.muted);txt('Page '+number,W-R-46,26,8,false,colors.muted)};
 const newPage=()=>{if(number){footer();pages.push(cmds.join('\n'))}number++;cmds=[];rect(0,H-15,W,15,colors.navy);y=H-42};
 const ensure=h=>{if(y-h<B)newPage()};
 const wrap=(s,width,size=10)=>{const chars=Math.max(14,Math.floor(width/(size*0.51)));const result=[];clean(s).split('\n').forEach(par=>{if(!par.trim()){result.push('');return}let cur='';par.split(/\s+/).forEach(word=>{if(!word)return;if((cur+' '+word).trim().length>chars&&cur){result.push(cur);cur=word}else cur=cur?cur+' '+word:word;while(cur.length>chars+14){result.push(cur.slice(0,chars));cur=cur.slice(chars)}});if(cur)result.push(cur)});return result.length?result:[''];};
 const paragraph=(s,{indent=0,size=10,bold=false,color=colors.ink,leading=14,after=5}={})=>{wrap(s,usable-indent,size).forEach(t=>{ensure(leading);txt(t,L+indent,y-size+2,size,bold,color);y-=leading});y-=after};
 const section=(s)=>{ensure(47);y-=11;rect(L,y-29,usable,31,colors.navy);txt(clean(s).toUpperCase(),L+12,y-19,12,true,colors.white);y-=42};
 const question=(s)=>{const lines=wrap(s,usable-18,11);ensure(Math.min(115,lines.length*15+23));y-=5;rect(L,y-Math.min(120,lines.length*15+13),3,Math.min(120,lines.length*15+13),colors.teal);lines.forEach(t=>{ensure(15);txt(t,L+12,y-10,11,true,colors.navy);y-=15});y-=8};
 const entryTitle=(s)=>{ensure(29);rect(L+10,y-25,usable-20,27,colors.pale);txt(s,L+19,y-17,10,true,colors.navy);y-=35};
 const value=(k,v,qid,indent=12)=>{if(v===undefined||v===null||v===''||(Array.isArray(v)&&!v.length))return;if(Array.isArray(v)){if(v.some(x=>x&&typeof x==='object')){v.forEach((x,i)=>{entryTitle('Entry '+(i+1));Object.entries(x||{}).forEach(([key,val])=>value(key,val,qid,indent+9))});return}paragraph(keyLabel(k,qid)+': '+v.join('; '),{indent,size:9.5});return}if(typeof v==='object'){paragraph(keyLabel(k,qid)+':',{indent,bold:true,size:9.5,after:2});Object.entries(v).forEach(([key,val])=>value(key,val,qid,indent+9));return}const title=keyLabel(k,qid);paragraph(title+': '+String(v),{indent,size:9.5,leading:13,after:5})};
 newPage();rect(L,y-67,usable,67,colors.navy);txt('Materials Commons',L+15,y-25,18,true,colors.white);txt('Infrastructure assessment questionnaire  |  Version '+clean(result.version||1),L+15,y-46,10,false,colors.white);y-=83;
 paragraph('Research project and daily business use',{size:11,color:colors.teal,bold:true,after:12});
 ensure(91);rect(L,y-89,usable,89,colors.pale);const info=[['Assessor',result.assessment?.Assessor],['Organisation',result.assessment?.Organisation],['Infrastructure',Array.isArray(result.assessment?.Infrastructure)?result.respondent.Profiles.map(x=>x==='Other'&&result.assessment?.Infrastructure?'Other: '+result.respondent.OtherProfile:x).join('; '):(result.assessment?.Infrastructure||'-')],['Date',result.assessment?.Date]];info.forEach(([key,val],i)=>txt(key+': '+clean(val||'-'),L+12,y-18-i*19,10,i===0,colors.ink));y-=105;
 let current='';result.answers.forEach(item=>{if(item.section!==current){current=item.section;section(current)}const title=item.question||item.questionId||'Question';const parts=title.split(/\n(.+)/s);question(parts[0]);if(parts[1]?.trim())paragraph(parts[1].trim(),{indent:12,size:9,color:colors.muted,after:10});const response=item.response||{};const values=Object.entries(response).filter(([,v])=>v!==''&&v!==null&&v!==undefined&&(!Array.isArray(v)||v.length));if(!values.length)paragraph('No response provided',{indent:12,color:colors.muted,size:9});else values.forEach(([k,v])=>value(k,v,item.questionId));y-=9;ensure(8);line(L,y,W-R,y,colors.line);y-=12});
 footer();pages.push(cmds.join('\n'));
 const objs=[null],add=s=>(objs.push(s),objs.length-1);const catalog=add(''),tree=add('');const f1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),f2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');const ids=[];
 pages.forEach(stream=>{stream+='\n';const bytes=new TextEncoder().encode(stream);const content=add('<< /Length '+bytes.length+' >>\nstream\n'+stream+'endstream');ids.push(add('<< /Type /Page /Parent '+tree+' 0 R /MediaBox [0 0 '+W+' '+H+'] /Resources << /Font << /F1 '+f1+' 0 R /F2 '+f2+' 0 R >> >> /Contents '+content+' 0 R >>'))});objs[catalog]='<< /Type /Catalog /Pages '+tree+' 0 R >>';objs[tree]='<< /Type /Pages /Kids ['+ids.map(id=>id+' 0 R').join(' ')+'] /Count '+ids.length+' >>';
 // Use byte offsets (not JavaScript UTF-16 lengths) for a standards-compliant PDF.
 let out='%PDF-1.4\n',offsets=[0];for(let i=1;i<objs.length;i++){offsets[i]=out.length;out+=i+' 0 obj\n'+objs[i]+'\nendobj\n'}const xref=out.length;out+='xref\n0 '+objs.length+'\n0000000000 65535 f \n';for(let i=1;i<objs.length;i++)out+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';out+='trailer\n<< /Size '+objs.length+' /Root '+catalog+' 0 R >>\nstartxref\n'+xref+'\n%%EOF\n';return new Blob([out],{type:'application/pdf'});
}
global.MaterialsCommonsPDF={makePdf};
})(typeof window==='undefined'?globalThis:window);
